# Generated by Django 3.0.8 on 2021-03-19 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20210319_2347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='car_tittle',
            new_name='car_title',
        ),
    ]
